# Generated by Django 2.1.7 on 2019-03-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_auto_20190314_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='address',
            new_name='name',
        ),
    ]
