# Generated by Django 2.1.7 on 2019-03-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0010_auto_20190317_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='task1.Shop', verbose_name='Shop'),
        ),
    ]
