# Generated by Django 2.1.7 on 2019-03-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0012_auto_20190321_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
